name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hello-image:latest

      - name: Build and push Docker image
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}  
        run: |
          docker build --build-arg SECRET_TOKEN=${SECRET_TOKEN} -t hello-image:1.0 .
          docker push hello-image:1.0 

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
